ignorePatterns:
  - "node_modules/**/*"
  - "public/**/*"
  - "cache/**/*"
extends:
  - react-app
  - plugin:prettier/recommended
plugins:
  - react-hooks
rules:
  prettier/prettier:
    - error
  react-hooks/rules-of-hooks: error # Checks rules of Hooks
  react-hooks/exhaustive-deps: warn # Checks effect dependencies
